### ISSUE TITLE
Feature request: color UI & highlighting

### ISSUE THREAD

**Issue by stevenhoneyman** [LonnyGomes/hexcurse#11]
I'd like to be able to change from the white UI to something different (so that the hex is different to the ascii and the rest of the UI).

Also would be really nice if there was an option/parameter to highlight/color change different hex strings (pixel/hexedit does this with --color for example, 00 is colored differently etc)

**Comment by Kerrigan29a** [comment]
I've created a pull request with this feature #16

**Comment by LonnyGomes** [comment]
Hey guys, all of the work was done within this commit, 31cbb71. Let me know if looks good. I took a look at hexedit and I like how it differentiates ascii characters. Do you think that's worth adding?

**Comment by LonnyGomes** [comment]
Closing this out for now. We can look at adding additional color options in the future.
