### ISSUE TITLE
Create a new release and update homebrew formula

### ISSUE THREAD

**Issue by Kerrigan29a** [LonnyGomes/hexcurse#21]
Please, create a new release version with the new features and update the [homebrew formula](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/hexcurse.rb)

**Comment by LonnyGomes** [comment]
@Kerrigan29a thanks for reminding me, I've been meaning to get to doing just that!

**Comment by LonnyGomes** [comment]
@Kerrigan29a I saw that you made the PR for homebrew. Thanks, closing this out.
