### ISSUE TITLE
Show help if no arguments are provided

### ISSUE THREAD

**Issue by LonnyGomes** [LonnyGomes/hexcurse#23]
Currently, if hexcurse is run without arguments it shows the ncurses UI and you must use the keyboard shortcuts to open the file you want to edit. It turns out this isn't that helpful. Instead, show the help if hex curse is run without arguments.

**Comment by sampumon** [comment]
Additionally, ctrl-q does not work in the empty editor, and you'll be stuck there. Even if you know that ctrl-q should exit, which I didn't the first time.

macOS 10.14.4 / hexcurse 1.60.0
