### ISSUE TITLE
hexcurse exit after failed save&exit

### ISSUE THREAD

**Issue by errge** [LonnyGomes/hexcurse#9]
When I try to edit a read-only file on the filesystem and choose exit, hexcurse asks me if I want to save it first.  So far so good, but when I choose yes, it tells me "bad permission" and then exits.  Therefore I lose all my current changes.  Instead, it should continue running, so I can handle the issue.  Either by getting permissions in an another terminal window or saving as a different filename.

**Comment by LonnyGomes** [comment]
Closing out as this was already merged into master.
